name: testing-functionality
run-name: Testing functionality after using TDD
on: [push]
jobs:
  test-functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun test